version: '3.8'

services:
  nginx:
    build:
      context: ./nginx
    container_name: nginx_container
    ports:
      - "80:80"
    networks:
      - notes-app
    depends_on:
      - django
    restart: always

  mysql:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: suv
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - notes-app
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uuser", "-ppassword"]
      interval: 10s
      timeout: 5s
      retries: 5

  django:
    build:
      context: .
    container_name: django_cont
    command: sh -c "python manage.py migrate --no-input && gunicorn notesapp.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - ./:/app
    working_dir: /app
    env_file:
      - .env
    restart: always
    ports:
      - "8000:8000"
    networks:
      - notes-app
    depends_on:
      mysql:
        condition: service_healthy


volumes:
  mysql-data:

networks:
  notes-app:
    